# Config file for drone simulation and field deployment

# Global simulation parameters
simulation:
  useMoosSimPid: true # Use MOOS-IvP Vechicle simulator
  time_warp: 1
  number_of_drones: 1

  ardupilot_ip: "0.0.0.0"
  ardupilot_protocol: "udp"
  fdm_port_in_default: 9002
  ardupilot_port_default: 14550

# Field deployment parameters
field:
  home_altitude: 106.1
  ardupilot_ip: "ttyACM0" # serial port
  ardupilot_port: "115200" # baudrate
  ardupilot_protocol: "serial"
  speed:
    max: 25 # m/s
    min: 6 # m/s

moos:
  datum:
    #lat: 63.3975168
    #lon: 10.1435321
    #lat: 59.38395
    #lon: 10.45145
    #Lahelle
    lat: 59.13192
    lon: 10.29235

  # MOOS-IvP parameters
  shore_ip: 100.96.81.36
  defaultPorts:
    DB: 9000
    PSHARE: 9202

missionParams:
  log_enabled: true # If true, the mission will be logged to a file
  mission_duration: 600 # s - The duration of the mission (20min)

  voronoi_search_enabled: false # If true, the Voronoi algorithm will be used to set the path for the drone, else TMSTC* will be used
    # else, the TMSTC* algorithm will be used to set the path for the drone
  voronoi_setpoint_method: gridsearch # The method used to set the path for the voronoi algorithm. Can be "gridsearch", "center" or "centroid"

  # The ratio between the region grid cell distance in the TMSTC* algorithm and the sensor range. The sensor range is the maximum distance from the drone that the sensor can detect fires
  # TMSTC_gridsizeSensorRangeRatio: 0.5
  TMSTC_gridsizeSensorRangeRatio: 0.4 # might work better in simulation
  TMSTC_config_vmax: 18 # [m/s] The maximum speed of the drone (to be used in the TMSTC* algorithm when calculating the grid travel time)
  TMSTC_config_phi_max_rad: 45 # [degrees] The maximum bank angle of the drone (to be used in the TMSTC* algorithm when calculating the grid travel time)
  TMSTC_point_filtering: true # If true, the TMSTC* algorithm will filter out the grid cells that are already visited when replanning
    # points not outside the search Area and in ignored region will always be removed.
  # Fire parameters:
  fire_file_default: "fires_field.txt" # The file containing the fire data if generate not set
  # fire_file_default: "fires_01.txt" # The file containing the fire data if generate not set
  fire_generate: true # If true, the fires will be generated randomly, otherwise they will be read from a file
  fire_count: 40 # The number of fires to be placed in the region at launch
  fire_sep_min: 10 # m - The minimum separation between fires
  fire_color: red # The color of the fire, or "vehicle" if the fire should take the color of the vehicle as well

  fire_spawn_count: 0 # The number of fires to spawn after the mission has started
  fire_spawn_interval: 300:500 # s - The time interval for which the delayed fires will be spawned (randomly) ( 0 <= [tmin,tmax] <= mission_duration)

  # Ignored region parameters
  ignoredRegion_file_default: "ignoredRegions.txt" # The file containing the ignored region data if generate not set
  # ignoredRegion_file_default   : "regions_c8_sep150.txt" # The file containing the ignored region data if generate not set
  ignoredRegion_generate: true # If true, the ignored regions will be generated randomly, otherwise they will be read from a file
  ignoredRegion_count: 1 # The number of ignored regions to be placed in the region at launch
  ignoredRegion_sep_min: 150 # m - The minimum separation between ignored regions
  ignoredRegion_spawn_count: 0 # The number of ignored regions to spawn after the mission has started
  ignoredRegion_spawn_interval: 300:500 # s - The time interval for which the delayed ignored regions will be spawned (randomly) ( 0 <= [tmin,tmax] <= mission_duration)

  # Mission operator parameters - For simulating many missions
  mission_operator_reset_delay: 2 # s - Delay between mission completion and reset in (actual) seconds

  mission_operator_TMSTC_missions: 2 # The number of TMSTC* missions to be run
  mission_operator_voronoi_missions: 0 # The number of VORONOI_SEARCH missions to be run

  # Region parameters: The region in which the mission is to be conducted
  # TOOL: https://www.keene.edu/campus/maps/tool/
  use_moos_region: false
  region_XY: 100,460:-700,-200:-700,-920:620,-920:700,-222 # Directly in moos format for tesing
  # region_lonlat: |
  #   10.1354027, 63.4005544
  #   10.1202106, 63.3930786
  #   10.1268196, 63.3852164
  #   10.1547146, 63.3869467
  #   10.1695633, 63.3984791
  #   10.1502943, 63.4049352

  # region_lonlat: |             # Stretched octagon
  #   10.1187944, 63.3949045
  #   10.1129580, 63.3923098
  #   10.1120996, 63.3864276
  #   10.1217127, 63.3841782
  #   10.1499081, 63.3840052
  #   10.1596069, 63.3867929
  #   10.1602077, 63.3924059
  #   10.1540709, 63.3949622

  region_lonlat: | # Larger region
    10.1356602, 63.4006697
    10.1259184, 63.3971146
    10.1233006, 63.3922521
    10.1484919, 63.3894265
    10.1663446, 63.3964228
    10.1657867, 63.4000164
    10.1519251, 63.4015728

  # region_lonlat: |  #  Testing Master_v2.0
  #   10.1402199, 63.3989018
  #   10.1470220, 63.4002037
  #   10.1508093, 63.3985463
  #   10.1488352, 63.3973356
  #   10.1472044, 63.3964516
  #   10.1456809, 63.3956348
  #   10.1426983, 63.3940492
  #   10.1379776, 63.3942126
  #   10.1344800, 63.3968936

  # Waypoint parameters
  # capture_radius: 50 # m  - The distance from the waypoint that the drone must be within to consider it captured
  capture_radius: 30 # works better in simulation
  slip_radius: 75 # m   (both currently modify sim parameters)

  # Grid parameters
  grid_cell_size: 10 # m - The distance between each waypoint in the grid
  grid_cell_max_count: 20 # Max number og visit before it is fully coloured
  grid_cell_decay_time: 5 # s - The decay rate of the grid cell value. Every x seconds it is decreased by 1 // 0 means no decay

  # Sensor parameters
  sensor_detect_pd: 1.0 # Probability of detection of fire
  sensor_radius_min: 20 # m - The farthest distance from the drone from which the drone has a possibility to detect fires with detect_pd
  sensor_radius_max: 30 # m - The distance from which after sensor_radius_min the probability of detection drops linearly to 0
  sensor_color: white # The color of the sensor circle/area
  sensor_altitude_max: 130 # m - The maximum altitude at which the sensor has a range of 100% (sensor_radius_max)
  sensor_radius_fixed: true # If true, the sensor radius will be fixed at sensor_radius, regardless of altitude

  # Collision avoidance parameters
  encounter_radius: 100 # m - The distance from the drone that the other drone must be within to consider it encountered
  near_miss_radius: 50 # m - The distance from the drone that the other drone must be within to consider it near missed
  collision_radius: 10 # m - The distance from the drone that the other drone must be within to consider it collided

drones:
  - name: "t1_ranger"
    color: "orange"
    start_orientaton_moos: # +x is east, +y is north [m] !!MOOS seems to double he distance,  so 50m east is a distance of 100 in MOOS!!
      x: 0
      y: 0
      hdg: 46 # deg
    # simulation: # Can be automated away (for now it is hardcoded)
    #   ardupilot_port: 14550
    #   fdm_port_in: 9002

  - name: "skyfollower"
    color: "hotpink"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: -100
      y: -5
      hdg: 36 # deg
    # simulation:
    #   ardupilot_port: 14560
    #   fdm_port_in: 9012

  - name: "skytrailer"
    color: "purple"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 100
      y: -5
      hdg: 56 # deg
    # simulation:
    #   ardupilot_port: 14570
    #   fdm_port_in: 9022

  - name: "sky4"
    color: "blue"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 100
      y: -200
      hdg: 56 # deg

  - name: "sky5"
    color: "red"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: -15
      y: 85
      hdg: 56 # deg

  - name: "sky6"
    color: "green"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 16
      y: -96
      hdg: 56 # deg

  - name: "sky7"
    color: "brown"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 95
      y: -100
      hdg: 56 # deg

  - name: "sky8"
    color: "magenta"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: 75
      y: 110
      hdg: 56 # deg

  - name: "sky9"
    color: "cyan"
    start_orientaton_moos: # +x is east, +y is north [m]
      x: -78
      y: -150
      hdg: 56 # deg
